### ISSUE TITLE
Found thus far

### ISSUE THREAD

**Issue by AnodeCathode** [aziel13/TechNodeFirmaCraftQuest#2]
- Add lives to all the quests for those who might want to turn hardcore mode on would be cool.
- Firepits quest is requesting a vanilla torch, not TFC.
- Handing out either 16 marble and 16 rock salt for the knapping quest is waay too generous. I'd suggest no flux stone or salt. Maybe just 16 of a lesser seen surface material. Basalt maybe?
- Stone axe quest is not working. There are 4 different types of stone axe heads depending on the rocktype used. Trying all 4 and they are not recognized.
- A water jug might be a bit much for a prize for Food and Water. Maybe the fish and the option of the corn, rye or wheat.
- Gold panning not completed yet? No item for completion.
- Not sure cooked foods are a great reward. Decay will eat into them pretty quickly.
- The iron age rewards are too rich. Finishing the quest tree would take an hour once you're ready and you'd end up with a lot of red/blue steel with very little effort.
- Immersive engineering - Might mention where you normally get the seeds you are giving as a reward.
- Not a big fan of the reward giving the ingredients for something back, like with the engineers hammer. Have you added up all the black/blue/red steel you're handing out? It should be considerably rarer. 

All in all, really like what I'm seeing. Would love to see more quest bags in the rewards that would mix up the returns a bit. Also more lives as quests for the hardcore mode setters. Also might want to think about the overall reward mix and how quickly someone might obtain them. This is supposed to be a hard pack and we wouldn't want the quests to turn it into easy mode. This is TNFC, not AS :)

Great stuff so far. Thanks for doing this.

**Comment by Bunsan** [comment]
I haven't been through it all, so I'll just offer a couple of additional comments. First is for the javelin quest. Maybe bring up that TFC has 3 new types of damage; crushing (hammer and maces), Slashing (Swords and Axes) and Piercing (arrows, javelins and knives) in addition to the generic damage of MC. See http://wiki.terrafirmacraft.com/Damage_Type for more details.

Mention that torches can be relit with a lit torch and put out by right clicking.

**Comment by AnodeCathode** [comment]
Hide Bed - Might mention that they need to kill a bear or a cow to get the large hide for the basic bed.
  Subquest name Primitive beding should be bedding.

**Comment by AnodeCathode** [comment]
Pottery - Instructions should also note that the ground cannot be dry. and clay deposit. No e

Wonder if this should have another part to it to fire the actual small items. Then they'd have the jug for the Food and Water quest later.

**Comment by AnodeCathode** [comment]
Food and Water - Some weird characters at the end of the instructions. Might also add that seaweed doesn't appear if you're very far north.

**Comment by AnodeCathode** [comment]
Understanding Food Basics - You are looking for a full stack of rye grain which is not going to come from the reward in the previous quest. Matching the reward is going to be difficult if there is no way to ignore the amount of the item.

**Comment by AnodeCathode** [comment]
Looking for Metals still appears not to have the item it needs (assuming it's the gold pan).

I'll leave this here. My original notes still stand for the most part. I'll have a look when you've got some of this squared away.

**Comment by aziel13** [comment]
I think I have fixed all the issues presented here.
